IGNITE-19410 Fixed node crash due to SecurityContext not being found during discovery message processing.
apache/ignite pull request #10701
Opened 2023-05-04 13:20 UTC by petrov-mg

Thank you for submitting the pull request to the Apache Ignite.

In order to streamline the review of the contribution 
we ask you to ensure the following steps have been taken:

### The Contribution Checklist
- [ ] There is a single JIRA ticket related to the pull request. 
- [ ] The web-link to the pull request is attached to the JIRA ticket.
- [ ] The JIRA ticket has the _Patch Available_ state.
- [ ] The pull request body describes changes that have been made. 
The description explains _WHAT_ and _WHY_ was made instead of _HOW_.
- [ ] The pull request title is treated as the final commit message. 
The following pattern must be used: `IGNITE-XXXX Change summary` where `XXXX` - number of JIRA issue.
- [ ] A reviewer has been mentioned through the JIRA comments 
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessandMaintainers)) 
- [ ] The pull request has been checked by the Teamcity Bot and 
the `green visa` attached to the JIRA ticket (see [TC.Bot: Check PR](https://mtcga.gridgain.com/prs.html))

### Notes
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute)
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules)
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines)
- [Apache Ignite Teamcity Bot](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+Teamcity+Bot)

If you need any help, please email dev@ignite.apache.org or ask anу advice on http://asf.slack.com _#ignite_ channel.

2023-05-19 11:20 UTC, timoninmaxim requested changes

2023-05-21 06:40 UTC, petrov-mg commented on modules/core/src/test/java/org/apache/ignite/internal/processors/security/NodeSecurityContextPropagationTest.java
> +    private boolean isNodeAddedMessageReceived(IgniteEx ignite, int nodeIdx) {
I refactored the `getReceivedMessages` method to use `Predicate` as its parameter. This made the test logic a bit clearer. But a separate method for checking whether an arbitrary message is a DiscoveryNodeAddedMessage message sill remains.

2023-05-21 06:40 UTC, petrov-mg commented on modules/core/src/test/java/org/apache/ignite/internal/processors/security/NodeSecurityContextPropagationTest.java
> +    private IgniteEx startClientNode(int idx) throws Exception {
Fixed.

2023-05-21 06:40 UTC, petrov-mg commented on modules/core/src/test/java/org/apache/ignite/internal/processors/security/NodeSecurityContextPropagationTest.java
> +            .setDataStorageConfiguration(new DataStorageConfiguration())
Fixed.

2023-05-21 06:40 UTC, petrov-mg commented on modules/core/src/main/java/org/apache/ignite/internal/managers/discovery/GridDiscoveryManager.java
> +        for (Collection<ClusterNode> top : topHist.values()) {
Fixed.

2023-05-23 15:22 UTC, timoninmaxim approved these changes

2023-05-25 08:25 UTC, merged