IGNITE-13876 Updated documentation for 2.9.1 release
apache/ignite pull request #8592
Opened 2020-12-18 13:05 UTC by ymolochkov

2020-12-18 16:39 UTC, Nikita-tech-writer commented on docs/_docs/monitoring-metrics/system-views.adoc
> +This view exposes information all available binary types.
```suggestion
This view exposes information about all available binary types.
```

2020-12-18 16:41 UTC, Nikita-tech-writer requested changes
Please see my suggesed change to your PR.

2020-12-18 17:12 UTC, ymolochkov commented
> Please see my suggesed change to your PR.

Thanks, applied your suggestion

2020-12-18 17:21 UTC, Nikita-tech-writer approved these changes

2020-12-18 17:22 UTC, Nikita-tech-writer approved these changes

2020-12-18 19:29 UTC, merged

2020-12-18 19:30 UTC, dmagda commented
@ymolochkov merged to the master! Please work with 2.9.1 release manage to cherry-pick the commit to the release branch. Once the vote is closed, ping me via email or Slack and I'll upload 2.9.1 docs to the website.

2020-12-21 08:43 UTC, ymolochkov commented
@dmagda but what should we do with docs if they are in separate branch (2.9-docs)? Create another branch for the same purposes or merge docs to the release branch?