IGNITE-14134 commit snapshot partition iterator
apache/ignite pull request #8767
Opened 2021-02-08 12:02 UTC by Mmuzaf

Thank you for submitting the pull request to the Apache Ignite.

In order to streamline the review of the contribution 
we ask you to ensure the following steps have been taken:

### The Contribution Checklist
- [ ] There is a single JIRA ticket related to the pull request. 
- [ ] The web-link to the pull request is attached to the JIRA ticket.
- [ ] The JIRA ticket has the _Patch Available_ state.
- [ ] The pull request body describes changes that have been made. 
The description explains _WHAT_ and _WHY_ was made instead of _HOW_.
- [ ] The pull request title is treated as the final commit message. 
The following pattern must be used: `IGNITE-XXXX Change summary` where `XXXX` - number of JIRA issue.
- [ ] A reviewer has been mentioned through the JIRA comments 
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessandMaintainers)) 
- [ ] The pull request has been checked by the Teamcity Bot and 
the `green visa` attached to the JIRA ticket (see [TC.Bot: Check PR](https://mtcga.gridgain.com/prs.html))

### Notes
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute)
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules)
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines)
- [Apache Ignite Teamcity Bot](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+Teamcity+Bot)

If you need any help, please email dev@ignite.apache.org or ask anу advice on http://asf.slack.com _#ignite_ channel.

2021-03-01 14:54 UTC, anton-vinogradov requested changes

2021-03-01 16:51 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +            store.sync();
Fixed. The `ensure` method is used in such cases through other parts of the source code.

2021-03-01 16:52 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +            // can avoid it here.
Fixed.

2021-03-01 16:52 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +        String consId,
Fixed.

2021-03-01 16:52 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +        File[] grps = nodePath.listFiles(path -> path.isDirectory() &&
Fixed.

2021-03-01 16:52 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +                path.getName().equalsIgnoreCase(cacheDirName(false, grpName))));
Agree, fixed.

2021-03-01 16:52 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AtomicBitSet.java
> +package org.apache.ignite.internal.processors.cache.persistence.snapshot;
I've rollbacked the changes related to the AtomicBitSet. `BitSet` used insted.

2021-03-01 16:53 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AtomicBitSet.java
> +class AtomicBitSet {
I've rollbacked the changes related to the AtomicBitSet. BitSet used instead.

2021-03-01 16:53 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +                    if (firstScan && rowsCnt == 0) {
Comment added.

2021-03-01 16:53 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +                    // on the second iteration.
I've updated the comment, please, take a look.

2021-03-01 16:53 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/AtomicBitSet.java
> +    public boolean touch(long off) {
I've rollbacked the changes related to the AtomicBitSet. BitSet used instead.

2021-03-01 16:53 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/IdleVerifyUtility.java
> +            // Object context may be null since the value bytes have been read directly from page.
Fixed.

2021-03-10 15:19 UTC, anton-vinogradov requested changes

2021-03-10 18:00 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/CacheDataRowAdapter.java
> +            catch (Exception e) {
Fixed.

2021-03-10 18:01 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/CacheDataRowAdapter.java
> +        assert isReady() : "ready";
Fixed.

2021-03-10 18:01 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +        private static void changeBit(BitSet bitSet, int idx) {
Fixed.

2021-03-10 18:01 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +        private static void changeBit(BitSet bitSet, int idx) {
Fixed.

2021-03-10 18:01 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +        private final BitSet markedPages;
Fixed.

2021-03-10 18:01 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +        /** Pages which already marked and postponed to be read on the second iteration. */
Fixed.

2021-03-10 18:01 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +    private static class PageScanIterator extends GridCloseableIteratorAdapter<CacheDataRow> {
Fixed.

2021-03-10 18:02 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +    public GridCloseableIterator<CacheDataRow> partitionRows(String snpName,
Fixed.

2021-03-10 18:04 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/CacheDataRowAdapter.java
> +            try {
Fixed.

2021-03-10 18:15 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +        long partCtr = cache.context().offheap().lastUpdatedPartitionCounter(0);
Fixed.

2021-03-10 18:16 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +                    boolean success0 = cached.initialValue(
Fixed.

2021-03-10 18:22 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +                if (!done.compareAndSet(false, true))
Fixed.

2021-03-10 18:23 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +    public void testClusterSnapshotCheckMissedHashes() throws Exception {
Fixed.

2021-03-10 18:25 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +    public void testClusterSnapshotCompareHashes() throws Exception {
Fixed.

2021-03-10 18:26 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +        Map<PartitionKeyV2, List<PartitionHashRecordV2>> hashes;
Fixed.

2021-03-10 18:26 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +        Map<PartitionKeyV2, List<PartitionHashRecordV2>> hashes;
Fixed.

2021-03-10 18:27 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +        Map<PartitionKeyV2, List<PartitionHashRecordV2>> hashes;
Fixed.

2021-03-10 18:31 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
> +                    cache.put(rnd.nextInt(15_000), new Value(new byte[rnd.nextInt(maxValSize)]));
Fixed.

2021-03-10 18:33 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +        public TestVisorBackupPartitionsTask(Map<PartitionKeyV2, List<PartitionHashRecordV2>> hashes) {
I doubt we need it here, since the amount of changes may only be greater.

2021-03-10 18:40 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
> +                assertEquals(12008, ((Value)row.value().value(coctx, false)).arr().length);
Fixed.

2021-03-10 18:41 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
> +            CacheObjectContext coctx = ignite.cachex("tx1").context().cacheObjectContext();
Fixed.

2021-03-10 18:41 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
> +            CacheObjectContext coctx = ignite.cachex("tx1").context().cacheObjectContext();
Fixed.

2021-03-10 18:46 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManagerSelfTest.java
> +    public void testSnapshotIteratorDirectIndirectCountersWithCacheGroup() throws Exception {
Removed.

2021-03-10 19:30 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/verify/IdleVerifyUtility.java
> +    public static Map<PartitionKeyV2, PartitionHashRecordV2> calculatePartitionHash(
Agree, looks odd. I've tried to keep all these changes `as is` to simplify the review, however, it looks like the method signature can by simplified without huge refactoring.

2021-03-10 19:35 UTC, Mmuzaf commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteSnapshotManager.java
> +            throw new IgniteCheckedException("Snapshot cache group not found [dir=" + snpDir.getAbsolutePath() + ", grpName=" + grpName + ']');
Fixed.

2021-03-12 09:42 UTC, anton-vinogradov approved these changes

2021-03-12 09:42 UTC, anton-vinogradov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +        assertNotNull(snpCheckHashes);
Let's assert they're not empty as well.

2021-03-12 09:48 UTC, Mmuzaf commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/persistence/snapshot/IgniteClusterSnapshotCheckTest.java
> +        assertNotNull(snpCheckHashes);
Fixed.

2021-03-13 13:47 UTC, merged