IGNITE-16024 B+Tree-related javadocs.
apache/ignite pull request #9702
Opened 2021-12-28 08:40 UTC by ibessonov

Thank you for submitting the pull request to the Apache Ignite.

In order to streamline the review of the contribution 
we ask you to ensure the following steps have been taken:

### The Contribution Checklist
- [ ] There is a single JIRA ticket related to the pull request. 
- [ ] The web-link to the pull request is attached to the JIRA ticket.
- [ ] The JIRA ticket has the _Patch Available_ state.
- [ ] The pull request body describes changes that have been made. 
The description explains _WHAT_ and _WHY_ was made instead of _HOW_.
- [ ] The pull request title is treated as the final commit message. 
The following pattern must be used: `IGNITE-XXXX Change summary` where `XXXX` - number of JIRA issue.
- [ ] A reviewer has been mentioned through the JIRA comments 
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessandMaintainers)) 
- [ ] The pull request has been checked by the Teamcity Bot and 
the `green visa` attached to the JIRA ticket (see [TC.Bot: Check PR](https://mtcga.gridgain.com/prs.html))

### Notes
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute)
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules)
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines)
- [Apache Ignite Teamcity Bot](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+Teamcity+Bot)

If you need any help, please email dev@ignite.apache.org or ask anу advice on http://asf.slack.com _#ignite_ channel.

2022-01-13 11:22 UTC, tkalkirill approved these changes

2022-01-17 16:54 UTC, SammyVimes requested changes

2022-01-17 16:54 UTC, SammyVimes commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
> + * It is described by a {@link BPlusIO#getMaxCount(long, int)} method is the corresponding IO. There should be no empty
```suggestion
 * It is defined by a {@link BPlusIO#getMaxCount(long, int)} method of the corresponding IO. There should be no empty
```

2022-01-17 16:54 UTC, SammyVimes commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/persistence/tree/BPlusTree.java
> + * All pages in the tree are devided into levels. Leaves are always at the level {@code 0}. Levels of inner pages are
```suggestion
 * All pages in the tree are divided into levels. Leaves are always at the level {@code 0}. Levels of inner pages are
```

2022-01-18 09:03 UTC, SammyVimes approved these changes
LGTM!

2022-01-18 11:48 UTC, merged